version: "3.8"
services:
  postgres-db:
    container_name: user-allocation-asi
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"